apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecnet-controller
  namespace: {{ include "ecnet.namespace" . }}
  labels:
    {{- include "ecnet.labels" . | nindent 4 }}
    app: ecnet-controller
    ecnetName: {{ .Values.ecnet.ecnetName }}
    {{ if .Values.ecnet.enforceSingleEcnet }}enforceSingleEcnet: "true"{{ end }}
spec:
  {{- if not .Values.ecnet.ecnetController.autoScale.enable }}
  replicas: {{ .Values.ecnet.ecnetController.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: ecnet-controller
      codebase: "{{ .Values.ecnet.repoServer.codebase }}"
  template:
    metadata:
      labels:
        {{- include "ecnet.labels" . | nindent 8 }}
        app: ecnet-controller
        codebase: "{{ .Values.ecnet.repoServer.codebase }}"
  {{- if .Values.ecnet.ecnetController.podLabels }}
  {{- toYaml .Values.ecnet.ecnetController.podLabels | nindent 8 }}
  {{- end }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
    spec:
      {{- if .Values.ecnet.ecnetController.affinity }}
      affinity:
      {{- toYaml .Values.ecnet.ecnetController.affinity | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      serviceAccountName: {{ .Release.Name }}
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      initContainers:
        - name: init
          image: {{ .Values.ecnet.curlImage }}
          command: ["curl", "http://ecnet-bootstrap.{{ include "ecnet.namespace" . }}:9091/healthz", "--connect-timeout", "2", "--retry", "50", "--retry-connrefused", "--retry-delay", "5"]
      containers:
        - name: repo
          image: {{ $.Values.ecnet.repoServer.image }}
          imagePullPolicy: {{ $.Values.ecnet.image.pullPolicy }}
          ports:
            - name: "repo"
              containerPort: {{ .Values.ecnet.proxyServerPort }}
          command: ['pipy']
          args: [
            "--admin-port={{ .Values.ecnet.proxyServerPort }}",
          ]
        - name: ctrl
          image: "{{ include "ecnetController.image" . }}"
          imagePullPolicy: {{ .Values.ecnet.image.pullPolicy }}
          ports:
            - name: "admin-port"
              containerPort: 15000
            - name: "metrics"
              containerPort: 9091
          command: ['/ecnet-controller']
          args: [
            "--verbosity", "{{.Values.ecnet.controllerLogLevel}}",
            "--ecnet-namespace", "{{ include "ecnet.namespace" . }}",
            "--ecnet-version", "{{ .Chart.AppVersion }}",
            "--ecnet-service-account", "{{ .Release.Name }}",
            "--ecnet-name", "{{.Values.ecnet.ecnetName}}",
            "--trust-domain", "{{.Values.ecnet.trustDomain}}",
          ]
          resources:
            limits:
              cpu: "{{.Values.ecnet.ecnetController.resource.limits.cpu}}"
              memory: "{{.Values.ecnet.ecnetController.resource.limits.memory}}"
            requests:
              cpu: "{{.Values.ecnet.ecnetController.resource.requests.cpu}}"
              memory: "{{.Values.ecnet.ecnetController.resource.requests.memory}}"
          readinessProbe:
            initialDelaySeconds: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /health/ready
              port: 9091
          livenessProbe:
            initialDelaySeconds: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /health/alive
              port: 9091
          env:
            - name: CONTROLLER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
    {{- if .Values.ecnet.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.ecnet.imagePullSecrets | indent 8 }}
    {{- end }}
      {{- if .Values.ecnet.ecnetController.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.ecnet.ecnetController.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ecnet.ecnetController.tolerations }}
      tolerations:
      {{- toYaml .Values.ecnet.ecnetController.tolerations | nindent 8 }}
      {{- end }}
